### ISSUE TITLE
FATAL: Failed to submit draw command buffer operations to graphics queue

### ISSUE THREAD

**Issue by kotleni** [kosude/minecraft_vk#1]
```bash
[2025-02-22 17:18:13] Instantiating resource manager for base path: "/home/kotleni/Projects/minecraft_vk/build/resources"
[2025-02-22 17:18:13] Creating GLFW window with dims 720x540, name "Minecraft Vulkan"
[2025-02-22 17:18:13] Validating required instance extensions...
        Available extensions:
                VK_KHR_device_group_creation
                VK_KHR_display
                VK_KHR_external_fence_capabilities
                VK_KHR_external_memory_capabilities
                VK_KHR_external_semaphore_capabilities
                VK_KHR_get_display_properties2
                VK_KHR_get_physical_device_properties2
                VK_KHR_get_surface_capabilities2
                VK_KHR_surface
                VK_KHR_surface_protected_capabilities
                VK_KHR_wayland_surface
                VK_KHR_xcb_surface
                VK_KHR_xlib_surface
                VK_EXT_acquire_drm_display
                VK_EXT_acquire_xlib_display
                VK_EXT_debug_report
                VK_EXT_debug_utils
                VK_EXT_direct_mode_display
                VK_EXT_display_surface_counter
                VK_EXT_surface_maintenance1
                VK_EXT_swapchain_colorspace
                VK_NV_display_stereo
                VK_EXT_headless_surface
                VK_KHR_portability_enumeration
                VK_LUNARG_direct_driver_loading
        Required (enabled) extensions:
                VK_KHR_surface
                VK_KHR_xcb_surface
[2025-02-22 17:18:13] Device manager found 1 physical device(s).
[2025-02-22 17:18:13] Using physical device (GPU): "NVIDIA GeForce GTX 1070"
[2025-02-22 17:18:13] Device manager found queue family indices for chosen physical device "NVIDIA GeForce GTX 1070":
        Graphics: 0
        Present:  0
        Compute:  0
        Transfer: 0
[2025-02-22 17:18:13] Loaded model "cube"
[2025-02-22 17:18:13] Loaded model "monkey"
[2025-02-22 17:18:13] Loaded material "grass_block"
[2025-02-22 17:18:13] Loaded material "monkey"
[2025-02-22 17:18:13] Loaded pipeline "g_monkey"
[2025-02-22 17:18:13] Loaded pipeline "g_simple"
[2025-02-22 17:18:13] Loaded pipeline "g_wireframe"
[2025-02-22 17:18:13] Loaded shader "monkey" which programs 2 stages
[2025-02-22 17:18:13] Loaded shader "simple" which programs 2 stages
[2025-02-22 17:18:13] Loaded shader "simple" which programs 2 stages
[2025-02-22 17:18:13] Building 3 graphics pipelines
[2025-02-22 17:18:13] Created new descriptor pool with 3 maximum descriptor sets and 3 pool size descriptor(s).
[2025-02-22 17:18:13] Entering main loop...
[2025-02-22 17:18:18] FATAL: Failed to submit draw command buffer operations to graphics queue
terminate called after throwing an instance of 'std::runtime_error*'
Aborted (core dumped)

```

**Comment by kosude** [comment]
Hi, thanks for reporting this. Unfortunately this project hasn't got the best in-built debugging since I haven't worked on it in a while so it may help to change these lines:

https://github.com/kosude/minecraft_vk/blob/130fd2275ec62aa4c11bfb6ccd3b5c2afffed590/engine/renderer/swapchain.cpp#L97-L99

so that you can find out what `vkQueueSubmit` is returning. Something like this works:
```c
VkResult r = vkQueueSubmit(_device.GetGraphicsQueue(), 1, &submit_info, _in_flight_fences[_current_frame]);
```

Could you report back with what `r` gets set to?

**Comment by kotleni** [comment]
@kosude Thanks for your attention.
`vkQueueSubmit` returns `VK_ERROR_DEVICE_LOST`

**Comment by kotleni** [comment]
I don't know how (maybe installed random vulkan package) but now i see some vk validation errors in logs!

<details>
<summary>Validation errors log</summary>

```bash
[2025-02-25 12:50:52] ERROR: VALIDATION: Validation Error: [ VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01971 ] Object 0: handle = 0x5555560b98c0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x869e76c5 | vkCmdBindDescriptorSets(): pDynamicOffsets[0] is 64, but must be a multiple of device limit minUniformBufferOffsetAlignment 256.
The Vulkan spec states: Each element of pDynamicOffsets which corresponds to a descriptor binding with type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01971)
[2025-02-25 12:50:52] ERROR: VALIDATION: Validation Error: [ VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01971 ] Object 0: handle = 0x5555560bd0e0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x869e76c5 | vkCmdBindDescriptorSets(): pDynamicOffsets[0] is 64, but must be a multiple of device limit minUniformBufferOffsetAlignment 256.
The Vulkan spec states: Each element of pDynamicOffsets which corresponds to a descriptor binding with type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01971)
[2025-02-25 12:50:52] ERROR: VALIDATION: Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0x2e2941000000001f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations.
The Vulkan spec states: If semaphore is not VK_NULL_HANDLE, it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
[2025-02-25 12:50:52] ERROR: VALIDATION: Validation Error: [ VUID-vkBeginCommandBuffer-commandBuffer-00049 ] Object 0: handle = 0x5555560b98c0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x84029a9f | vkBeginCommandBuffer():  on active VkCommandBuffer 0x5555560b98c0[] before it has completed. You must check command buffer fence before this call.
The Vulkan spec states: commandBuffer must not be in the recording or pending state (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkBeginCommandBuffer-commandBuffer-00049)
[2025-02-25 12:50:52] ERROR: VALIDATION: Validation Error: [ VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01971 ] Object 0: handle = 0x5555560b98c0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x869e76c5 | vkCmdBindDescriptorSets(): pDynamicOffsets[0] is 64, but must be a multiple of device limit minUniformBufferOffsetAlignment 256.
The Vulkan spec states: Each element of pDynamicOffsets which corresponds to a descriptor binding with type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01971)
[2025-02-25 12:50:52] ERROR: VALIDATION: Validation Error: [ VUID-vkResetFences-pFences-01123 ] Object 0: handle = 0xc4f3070000000021, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0x68a5074e | vkResetFences(): pFences[0] (VkFence 0xc4f3070000000021[]) is in use.
The Vulkan spec states: Each element of pFences must not be currently associated with any queue command that has not yet completed execution on that queue (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkResetFences-pFences-01123)
[2025-02-25 12:50:52] ERROR: VALIDATION: Validation Error: [ VUID-vkQueueSubmit-pCommandBuffers-00071 ] | MessageID = 0x2e2f4d65 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] VkCommandBuffer 0x5555560b98c0[] is already in use and is not marked for simultaneous use.
The Vulkan spec states: If any element of the pCommandBuffers member of any element of pSubmits was not recorded with the VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT, it must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkQueueSubmit-pCommandBuffers-00071)
[2025-02-25 12:50:52] ERROR: VALIDATION: Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0x301e6c0000000022, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations.
The Vulkan spec states: If semaphore is not VK_NULL_HANDLE, it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
[2025-02-25 12:50:52] ERROR: VALIDATION: Validation Error: [ VUID-vkBeginCommandBuffer-commandBuffer-00049 ] Object 0: handle = 0x5555560bd0e0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x84029a9f | vkBeginCommandBuffer():  on active VkCommandBuffer 0x5555560bd0e0[] before it has completed. You must check command buffer fence before this call.
The Vulkan spec states: commandBuffer must not be in the recording or pending state (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkBeginCommandBuffer-commandBuffer-00049)
[2025-02-25 12:50:52] ERROR: VALIDATION: Validation Error: [ VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01971 ] Object 0: handle = 0x5555560bd0e0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x869e76c5 | vkCmdBindDescriptorSets(): pDynamicOffsets[0] is 64, but must be a multiple of device limit minUniformBufferOffsetAlignment 256.
The Vulkan spec states: Each element of pDynamicOffsets which corresponds to a descriptor binding with type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01971)
[2025-02-25 12:50:52] ERROR: VALIDATION: Validation Error: [ VUID-vkResetFences-pFences-01123 ] Object 0: handle = 0xb991fa0000000024, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0x68a5074e | vkResetFences(): pFences[0] (VkFence 0xb991fa0000000024[]) is in use.
The Vulkan spec states: Each element of pFences must not be currently associated with any queue command that has not yet completed execution on that queue (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkResetFences-pFences-01123)
[2025-02-25 12:50:52] ERROR: VALIDATION: Validation Error: [ VUID-vkQueueSubmit-pCommandBuffers-00071 ] | MessageID = 0x2e2f4d65 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] VkCommandBuffer 0x5555560bd0e0[] is already in use and is not marked for simultaneous use.
The Vulkan spec states: If any element of the pCommandBuffers member of any element of pSubmits was not recorded with the VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT, it must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkQueueSubmit-pCommandBuffers-00071)
[2025-02-25 12:50:53] ERROR: VALIDATION: Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01779 ] Object 0: handle = 0x2e2941000000001f, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0x5717e75b | vkAcquireNextImageKHR():  Semaphore must not have any pending operations.
The Vulkan spec states: If semaphore is not VK_NULL_HANDLE, it must not have any uncompleted signal or wait operations pending (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01779)
[2025-02-25 12:50:57] ERROR: VALIDATION: Validation Error: [ VUID-vkBeginCommandBuffer-commandBuffer-00049 ] Object 0: handle = 0x5555560b98c0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x84029a9f | vkBeginCommandBuffer():  on active VkCommandBuffer 0x5555560b98c0[] before it has completed. You must check command buffer fence before this call.
The Vulkan spec states: commandBuffer must not be in the recording or pending state (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkBeginCommandBuffer-commandBuffer-00049)
[2025-02-25 12:50:57] ERROR: VALIDATION: Validation Error: [ VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01971 ] Object 0: handle = 0x5555560b98c0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x869e76c5 | vkCmdBindDescriptorSets(): pDynamicOffsets[0] is 64, but must be a multiple of device limit minUniformBufferOffsetAlignment 256.
The Vulkan spec states: Each element of pDynamicOffsets which corresponds to a descriptor binding with type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBindDescriptorSets-pDynamicOffsets-01971)
[2025-02-25 12:50:57] ERROR: VALIDATION: Validation Error: [ VUID-vkResetFences-pFences-01123 ] Object 0: handle = 0xc4f3070000000021, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0x68a5074e | vkResetFences(): pFences[0] (VkFence 0xc4f3070000000021[]) is in use.
The Vulkan spec states: Each element of pFences must not be currently associated with any queue command that has not yet completed execution on that queue (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkResetFences-pFences-01123)
[2025-02-25 12:50:57] ERROR: VALIDATION: Validation Error: [ VUID-vkQueueSubmit-pCommandBuffers-00071 ] | MessageID = 0x2e2f4d65 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] VkCommandBuffer 0x5555560b98c0[] is already in use and is not marked for simultaneous use.
The Vulkan spec states: If any element of the pCommandBuffers member of any element of pSubmits was not recorded with the VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT, it must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkQueueSubmit-pCommandBuffers-00071)
```

</details>

**Comment by kosude** [comment]
@kotleni, I've opened the [`1-combuf-submit-err`](https://github.com/kosude/minecraft_vk/tree/1-combuf-submit-err) branch for this, so development on this issue can be tracked there.

So far, https://github.com/kosude/minecraft_vk/commit/c31722763f0b66c507d445da1f114e6f83df9b8f *should* fix *some* of the validation errors, namely the ones related to misaligned offsets. These were due to me relying on a 4-byte minimum alignment which is a far cry from the 256 byte boundaries on some (all?) Nvidia cards!

That said I'm not 100% sure as I don't have direct access to an Nvidia GPU for testing, so let me know if the amount of errors isn't reduced on your end.

I'll continue to work on this although it might not be too frequent since I'm pretty busy with coursework and stuff at the moment.

**Comment by kosude** [comment]
I just pushed a new commit 7b45183627881467019a1c238f62220f333200f0 to the [`1-combuf-submit-err`](https://github.com/kosude/minecraft_vk/tree/1-combuf-submit-err) branch, which fixes a mismatch between indexing semaphore lists using frame indices vs image indices.

Recently Vulkan updated the SDK for the validation layer to report unsafe use of presentation wait semaphores. This caused some new errors on my end, which this commit fixes. I figure this could have also indirectly caused some of the errors you're recieving - @kotleni, could you check if there's any notable differences in your output?

**Comment by kotleni** [comment]
Nah, I still have the same error when just building from the source code. (from new branch)

**Comment by kosude** [comment]
For diagnostics' sake (and also because it's been so long since I did graphics that I'm way worse at it now) I've simplified the code into a new branch, [`no-fif`](https://github.com/kosude/minecraft_vk/tree/no-fif), which doesn't implement multiple frames in flight.

Since a lot of the errors are synchronisation-related, and because synchronisation without pipelining is way simpler to diagnose, hopefully that'll speed this up a bit. The fact I can't test the changes myself is not really helping things :P

Anyway, is the output any better when running a build from that branch?

**Comment by kotleni** [comment]
@kosude, https://pastebin.com/Nx9PJxpL.
Is it worth it?

**Comment by kosude** [comment]
Interestingly the first time a swapchain is created is before loading resources, building pipelines etc. That's being done successfully as evident by the program not dying earlier.

When does that exception occur for you? Swapchain recreation isn't done unless the existing swapchain becomes outdated. In my testing that doesn't happen until the window is resized, but maybe it's somehow happening during the first frame on your end.

**Comment by kotleni** [comment]
@kosude I see a monkey on minecraft block with red background and after about 1 second it's just crashes.

**Comment by kosude** [comment]
My friend lended me an old Nvidia Quadro for testing this, and I've come up with commit 4c3d44874567b21739118bd9f18a6232cbe11fdb which seems to fix the issue on that card, when using the proprietary Nvidia drivers.

Can you let me know if that fixes it for you too? Note this is all still on [no-fif](https://github.com/kosude/minecraft_vk/tree/no-fif)

**Comment by kotleni** [comment]
@kotleni 
```
[2025-07-24 20:44:25] Entering main loop...
[2025-07-24 20:44:25] FATAL: Failed to create swap chain
terminate called after throwing an instance of 'std::runtime_error*'
Aborted                    (core dumped) ./game
```

:3

**Comment by kotleni** [comment]
@kosude yep, it's works!

<img width="977" height="767" alt="Image" src="https://github.com/user-attachments/assets/17caad6e-173c-41f1-99dd-e9b0d0bcd050" />

**Comment by kosude** [comment]
Glad that's finally over! I'll implement the fixes into the main branch soon (and clean it up heaps because the code for the renderer has become a mess) but for the time being I'll close the issue here.

I'll also pick up the pace in writing the actual game part of the project since at least now the renderer works for (hopefully) everyone. Thanks again for reporting, that was a big issue.
